### ISSUE TITLE
Error from https://localhost:4000/?mock=default-page

### ISSUE THREAD

**Issue by rsudworth** [microsoft/Msdyn365.Commerce.Online#16]
I've followed the readme file through and getting an error when trying https://localhost:4000/?mock=default-page. I get the following:

`{"name":"TypeError","message":"Express Caught an exception","stack":["TypeError: Cannot read property 'sameSiteRequired' of undefined","    at mapRequestContextWithRenderingContext (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\src\\_server\\parse-request.ts?2b6b:217:44)","    at _callee5$ (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\src\\_server\\index.ts?6325:324:82)","    at tryCatch (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:63:15)","    at Generator.invoke [as _invoke] (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:293:1)","    at Generator.next (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:118:1)","    at asyncGeneratorStep (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:3:1)","    at _next (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:25:1)","    at C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:32:1","    at new Promise (<anonymous>)","    at C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:21:1"],"originalStack":"TypeError: Cannot read property 'sameSiteRequired' of undefined\n    at mapRequestContextWithRenderingContext (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\src\\_server\\parse-request.ts?2b6b:217:44)\n    at _callee5$ (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\src\\_server\\index.ts?6325:324:82)\n    at tryCatch (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:63:15)\n    at Generator.invoke [as _invoke] (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:293:1)\n    at Generator.next (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\regenerator-runtime\\runtime.js?2408:118:1)\n    at asyncGeneratorStep (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:3:1)\n    at _next (C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:25:1)\n    at C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:32:1\n    at new Promise (<anonymous>)\n    at C:\\Users\\rsud\\source\\repos\\Msdyn365.Commerce.Online\\build\\webpack:\\node_modules\\@babel\\runtime\\helpers\\esm\\asyncToGenerator.js?c99a:21:1"}`

I am able to successfully run the following:
- https://localhost:4000/version
- https://localhost:4000/_sdk/allmodules

I don't currently have a website setup in D365 commerce, so I can't test if configuring a connection to this in the .env file errors (unless it is possible just to connect to retail server as I do have a D365 commerce development instance available).

I've tried the Yammer group provided by our Microsoft Partner contact, but had no response, and so I thought I'd ask for help on here.

**Comment by rsudworth** [comment]
Microsoft have advised that even though the page is running from mock data, there needs to be something against  MSDyn365_HOST in the .env file, e.g. MSDyn365_HOST=a

**Comment by rsudworth** [comment]
Has there been an update to the SDK to fix this or is the workaround still required?

**Comment by siddthesciencekid** [comment]
Closing this issue for now as we have a workaround. However, we have addressed this and have fixed it so that future versions of SDK will not rely on a HOST value being present to load mock pages.

**Comment by taimoor07** [comment]
I am new and I am still facing this issue. Set  MSDyn365_HOST=a does not fix the issue.
