### ISSUE TITLE
msdyn365 CLI

### ISSUE THREAD

**Issue by mknoos** [microsoft/Msdyn365.Commerce.Online#19]
When using *nix based systems. You have to change line-ending in file

`[...]/node_modules/@msdyn365-commerce/cli-internal/dist/cli.js`

from CRLF to LF to be able to use the CLI.

**Comment by danielkoch** [comment]
@mkelan: Quick question regarding this one: Where can I find the sources files of the mentioned file?

**Comment by mkelan** [comment]
@danielkoch Source files are not available in public repository. If you do yarn you will find the files on your local node_modules folder however
