### ISSUE TITLE
Could not generate data definition for file

### ISSUE THREAD

**Issue by VDinets** [microsoft/Msdyn365.Commerce.Online#27]
When I try to clone module checkout-shipping-address, I get an error in the console:
-- [2] Errors detected
-- Could not generate data definition ICustomCheckoutShippingAddressData for file: src/modules/custom-checkout-shipping-address/custom-checkout-shipping-address.data.ts RangeError: Maximum call stack size exceeded
-- Error in data-definition generator: RangeError: Maximum call stack size exceeded

I used "yarn msdyn365 clone checkout-shipping-address custom-checkout-shipping-address" command.

-- Using SDK version: 1.30.16
-- Using Module library version: 9.29.9
-- Using Retail proxy verson: 9.29.7

And when I try use on mock pages my custom clone module without any changes - I get this error:

Error: export not found

![image](https://user-images.githubusercontent.com/86613811/132712177-3d45a21a-7cb3-481b-9cf1-b9bb9e99b36f.png)

**Comment by VDinets** [comment]
Resolve by moving common & action and change imports

**Comment by mkelan** [comment]
@VDinets thanks for reporting and providing an update. glad you found a way to get past the issue.
