### ISSUE TITLE
Validate task not working for *nix systems

### ISSUE THREAD

**Issue by DShalima** [microsoft/Msdyn365.Commerce.Online#32]
I have issue running validate for my custom modules on MacOS (also tested on Ubunty). Receiving same error.

On windows everything works fine.

Line separator set correctly - all other tasks works fine.

<img width="783" alt="Screen Shot 2021-10-28 at 17 13 19" src="https://user-images.githubusercontent.com/92512868/139274246-0df3c1d2-6b09-401f-a0f1-3bca723d938f.png">

**Comment by mkelan** [comment]
@DShalima we currently dont support *nix based systems. please try recommendations from #19 to get unblocked. we have work in backlog to bring in this support.
