### ISSUE TITLE
Error on the run pipeline on CI

### ISSUE THREAD

**Issue by VDinets** [microsoft/Msdyn365.Commerce.Online#35]
Good day. 
After the last update to version 9.32, I get an error almost everyone runs the build pack pipeline.
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

 I use this article to setup the pipeline https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/set-up-code-sharing-build-pipeline.

**Comment by samjarawan** [comment]
Just FYI that the documentation is now updated.

**Comment by VDinets** [comment]
fixed
