### ISSUE TITLE
yarn msdyn365 add-module <Modulename> Error  

### ISSUE THREAD

**Issue by Jeyavijay** [microsoft/Msdyn365.Commerce.Online#39]
Hi Team,

System OS - macOS Big Sur 11.3
Yarn version - 1.22.17
node version - 6.14.15

I am able to start the server and view the modules and retail server in my local host.
When I try to add a new module I am getting this error. Can you please guide to add an new module

$ /Users/ladmin/Documents/D365-Commerce/Source/Msdyn365.Commerce.Online/node_modules/.bin/msdyn365 add-module campaignBanner
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Thanks in advance

**Comment by VDinets** [comment]
Try to use this https://github.com/microsoft/Msdyn365.Commerce.Online/issues/19

**Comment by mkelan** [comment]
Thanks @VDinets. @Jeyavijay our scripts currently does not support *nix based systems. please follow the guidance from the #19 to get unblocked.
