### ISSUE TITLE
Required Node Version not listed in Readme

### ISSUE THREAD

**Issue by joelshaffer** [microsoft/Msdyn365.Commerce.Online#41]
The Readme instructs the user to:

> Install latest version of [NodeJS](https://nodejs.org/en/download/)

But the project only supports version 12 of Node as called out in the Microsoft docs:

> Version 12.x is the current supported version.
_Source: [Setup Dev Environment](https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/setup-dev-environment#install-nodejs)_

**Comment by mkelan** [comment]
Thanks for pointing out, its fixed now.
