### ISSUE TITLE
Command not found "yarn" on self-hosted agent

### ISSUE THREAD

**Issue by aaronstackpole** [microsoft/Msdyn365.Commerce.Online#42]
After switching to self-hosted agent, I am unable to get PowerShell to recognize the command "yarn".

Yarn has been installed globally and the PATH environment variable has been set. When running YARN on PowerShell prompt or CMD prompt on the desktop, it works. When executing in the context of the Azure DevOps Agent, it does not work.

I have also tried adding "npm install --global yarn" to the build script, and the log shows it installs yarn, but then fails on the command to execute yarn on the very next step.

Please provide guidance on how to configure Azure DevOps Self-Hosted Agent to run yarn commands.

**Comment by mkelan** [comment]
Closing as this is a very old request and assuming its resolved. This is not actively monitored. for future reference, kindly use https://community.dynamics.com/365/commerce/f/dynamics-365-commerce-forum
