### ISSUE TITLE
Cart not getting updated once added the product to cart via CSU.

### ISSUE THREAD

**Issue by Jeyavijay** [microsoft/Msdyn365.Commerce.Online#47]
Hi Team,

We have added the add to cart api call in the Product.tsx file. The API call was happening successfully but the cart notification and Cartline items are not being updated automatically. Once we refresh the page it is updating.
What needs to done for updating the Cart notifications and cart line item after the successful api call?

Can anyone suggest what method/dataactions need to be called after the successful  API call?

Any suggestion will be really helpfull.

Thanks in Advance

![Product File](https://user-images.githubusercontent.com/13938507/165039923-1b0b0785-5a27-44aa-bd43-8b17f8dcbcd7.png)

**Comment by mkelan** [comment]
Closing this old thread. Please use https://community.dynamics.com/365/commerce/f/dynamics-365-commerce-forum as this is not actively monitored
