### ISSUE TITLE
Unable to build after upgrading to Node 16 +

### ISSUE THREAD

**Issue by AmanSonii** [microsoft/Msdyn365.Commerce.Online#49]
Hi Team,

Recently I upgraded the node version on local machine to 16.15.0. After installing the updated version I am encountering the following error while running the yarn start command. I have tried deleting the node module, build and yarn.lock files as well but it didn't work.

I would really appreciate the suggestions to resolve these.

**ApplicationInsights:An invalid instrumentation key was provided. There may be resulting telemetry loss [ ' ' ]

\build\webpack:\lib\module-registration.js?44dd:2743
                binding.dataActions[actionPath] = undefined;
                                    ^
ReferenceError: actionPath is not defined
    at Module.registerAllModules (\build\webpack:\lib\module-registration.js?44dd:2743:37)
    at Module../node_modules/@msdyn365-commerce/bootloader/entry/bootstrap.js (\build\webpack:\node_modules\@msdyn365-commerce\bootloader\entry\bootstrap.js?d994:189:35)**

ERROR in ./lib/module-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/accordion/dist/lib/modules/accordion-item/accordion-item' in 'lib'
 @ ./lib/module-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client
ERROR in ./lib/view-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/accordion/dist/lib/modules/accordion-item/accordion-item.view.js' in '\lib'
 @ ./lib/view-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/module-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/accordion/dist/lib/modules/accordion/accordion' in '\lib'
 @ ./lib/module-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/view-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/accordion/dist/lib/modules/accordion/accordion.view.js' in '\lib'
 @ ./lib/view-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/module-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/account-management/dist/lib/modules/aad-generic/aad-generic' in 'lib'
 @ ./lib/module-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/view-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/account-management/dist/lib/modules/aad-generic/aad-generic.view.js' in '\lib'
 @ ./lib/view-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/module-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/account-management/dist/lib/modules/account-address-tile/account-address-tile' in '\lib'
 @ ./lib/module-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/view-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/account-management/dist/lib/modules/account-address-tile/account-address-tile.view.js' in '\lib'
 @ ./lib/view-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/module-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/account-management/dist/lib/modules/account-customer-balance-tile/account-customer-balance-tile' in '\lib'
 @ ./lib/module-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/view-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/account-management/dist/lib/modules/account-customer-balance-tile/account-customer-balance-tile.view.js' in '\lib'
 @ ./lib/view-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/module-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/account-management/dist/lib/modules/account-customer-balance/account-customer-balance' in '\lib'
 @ ./lib/module-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/view-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/account-management/dist/lib/modules/account-customer-balance/account-customer-balance.view.js' in '\lib'
 @ ./lib/view-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/module-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/account-management/dist/lib/modules/account-generic-tile/account-generic-tile' in '\lib'
 @ ./lib/module-registration.js
 @ ./node_modules/@msdyn365-commerce/bootloader/entry/client.js
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./node_modules/@msdyn365-commerce/bootloader/entry/webpack-public-path.js webpack-dev-server/client?http://localhost:4001/ ./node_modules/@msdyn365-commerce/bootloader/entry/client

ERROR in ./lib/view-registration.js
Module not found: Error: Can't resolve 'hoisted/@msdyn365-commerce-modules/account-management/dist/lib/modules/account-generic-tile/account-generic-tile.view.js' in '\lib'
 @ ./lib/view-registration.js

Thanks,
Aman

**Comment by mkelan** [comment]
@AmanSonii apologies, we dont monitor this forum regularly. Is this issue resolved or are you still blocked? If this is still an issue, can you please create a support ticket so we can investigate and get you unblocked?

**Comment by AmanSonii** [comment]
Hi @mkelan,
Thanks for reaching out. Just wanted to let you know that I had resolved the issue. It was caused by a corrupt node version. I had to reinstall the node version with all the dependencies to make it work.

Thanks
Aman

**Comment by AmanSonii** [comment]
t was caused by a corrupt node version. I had to reinstall the node version with all the dependencies to make it work.
