### ISSUE TITLE
Cannot log in or add products to cart

### ISSUE THREAD

**Issue by barlowdw** [microsoft/Msdyn365.Commerce.Online#5]
I have setup a development environment and update .env to use my test e-Commerce environment. I am able to browse products. I am however not able to add a product to my cart. When I try to login I am prompted with the normal login page, but after logging in I receive the following error message:

500
The server encountered an internal error or misconfiguration and was unable to complete your request.

If I use the e-Commerce site using the normal URL and not the retail proxy running on the development machine then I am able to login.

**Comment by mkelan** [comment]
Hi, add to cart should not require a sign-in. When you add to cart, do you see a network call go out from your browser? does that call succeed? 

Also can you use the Yammer channel instead? The issue tracker here is not monitored.

**Comment by barlowdw** [comment]
Hi. I was trying to reproduce the issue with adding cart lines. Waited for all network request to finish. Now works to add a cart line. However when I try to use guest checkout and enter an address it does is not able to retrieve delivery options. I am able to do this if I am not using the retail proxy.

The request: https://parecomm5ad4ba92b8ad17e9ret.cloud.retail.dynamics.com/Commerce/Carts('lcwn5rnIo9poWuWQmm64DjHMOSe1Ta9Z')/GetDeliveryOptions?$top=1000&api-version=7.3

Fails with error code 400.

`{
  "TypeName": "CommerceException",
  "Exception": "{\r\n  \"ErrorResourceId\": \"Microsoft_Dynamics_Internal_Server_Error\",\r\n  \"LocalizedMessage\": \"An error occurred on server while processing this request.\"\r\n}",
  "CorrelationId": "f64851e0-20e9-4083-9634-811a9c585217"
}`

I have requested access to the yammer group and will move the issue there as soon as I can.

**Comment by mkelan** [comment]
Hi Derrick, what version of SSK/SDK/Retail Proxy/Retail Server are you using? Also can you share your live url for me to check? thanks!

**Comment by barlowdw** [comment]
HI Mkelan,

I'm using the latest version of master branch. See version information below:

Live url: https://parecomm-eval.commerce.dynamics.com/

.env file for dev environment below:

Looking at about of Dynamics 365 Commerce just gives me this: Version {version}

`{
  "packageName": "Msdyn365.Commerce.Online",
  "version": "1.0.0",
  "submissionId": "unknown",
  "build": {},
  "buildTime": "2020-05-11 16:12:29",
  "buildVersion": "013acc",
  "MSDyn365-Commerce": [
    {
      "packageName": "action-internal",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12"
        }
      ]
    },
    {
      "packageName": "bootloader",
      "versionDetails": [
        {
          "rootPackageVersion": "^1.0.0",
          "hoistedVersion": "1.21.12"
        }
      ]
    },
    {
      "packageName": "build-scripts-internal",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12",
          "@msdyn365-commerce-bootloader-package-json-version": "1.21.12",
          "@msdyn365-commerce-bootloader-node-modules-version": "HOISTED: Using version 1.21.12"
        }
      ]
    },
    {
      "packageName": "cache-internal",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12"
        }
      ]
    },
    {
      "packageName": "cli-internal",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12",
          "@msdyn365-commerce-bootloader-package-json-version": "1.21.12",
          "@msdyn365-commerce-bootloader-node-modules-version": "HOISTED: Using version 1.21.12"
        }
      ]
    },
    {
      "packageName": "cli-template-internal",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12"
        }
      ]
    },
    {
      "packageName": "commerce-entities",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15"
        }
      ]
    },
    {
      "packageName": "components",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15"
        }
      ]
    },
    {
      "packageName": "core",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12",
          "@msdyn365-commerce-bootloader-package-json-version": "1.21.12",
          "@msdyn365-commerce-bootloader-node-modules-version": "HOISTED: Using version 1.21.12"
        }
      ]
    },
    {
      "packageName": "core-internal",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12"
        }
      ]
    },
    {
      "packageName": "definition-generator-internal",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12",
          "@msdyn365-commerce-bootloader-package-json-version": "1.21.12",
          "@msdyn365-commerce-bootloader-node-modules-version": "HOISTED: Using version 1.21.12"
        }
      ]
    },
    {
      "packageName": "global-state",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15"
        }
      ]
    },
    {
      "packageName": "release-scripts",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12",
          "@msdyn365-commerce-bootloader-package-json-version": "1.21.12",
          "@msdyn365-commerce-bootloader-node-modules-version": "HOISTED: Using version 1.21.12"
        }
      ]
    },
    {
      "packageName": "retail-proxy",
      "versionDetails": [
        {
          "rootPackageVersion": "9.20.5",
          "hoistedVersion": "9.20.5"
        }
      ]
    },
    {
      "packageName": "runtime-internal",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12",
          "@msdyn365-commerce-bootloader-package-json-version": "1.21.12",
          "@msdyn365-commerce-bootloader-node-modules-version": "HOISTED: Using version 1.21.12"
        }
      ]
    },
    {
      "packageName": "telemetry-internal",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12"
        }
      ]
    },
    {
      "packageName": "theming-internal",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12"
        }
      ]
    },
    {
      "packageName": "tslint-rules",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12",
          "@msdyn365-commerce-bootloader-package-json-version": "1.21.12",
          "@msdyn365-commerce-bootloader-node-modules-version": "HOISTED: Using version 1.21.12"
        }
      ]
    },
    {
      "packageName": "utilities-internal",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12",
          "@msdyn365-commerce-bootloader-package-json-version": "1.21.12",
          "@msdyn365-commerce-bootloader-node-modules-version": "HOISTED: Using version 1.21.12"
        }
      ]
    }
  ],
  "MSDyn365-Commerce-Modules": [
    {
      "packageName": "accordion",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "account-management",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "address",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "autosuggest",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "bopis",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "bopis-utilities",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15"
        }
      ]
    },
    {
      "packageName": "buybox",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "carousel",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "cart",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "checkout",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "checkout-utilities",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "content-block",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "cookie-compliance",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "core-components",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "1.21.12"
        }
      ]
    },
    {
      "packageName": "data-types",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "definitions",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15"
        }
      ]
    },
    {
      "packageName": "fabrikam-design-kit",
      "versionDetails": [
        {
          "rootPackageVersion": "9.20.15",
          "hoistedVersion": "9.20.15"
        }
      ]
    },
    {
      "packageName": "footer",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "header",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "media-gallery",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "navigation-menu",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "order-management",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "order-summary-utilities",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15"
        }
      ]
    },
    {
      "packageName": "page-summary",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "product-collection",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "product-specification",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "promo-banner",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "ratings-reviews",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "resources",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "retail-actions",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "search",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "search-result-container",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "search-utilities",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15"
        }
      ]
    },
    {
      "packageName": "spacer",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "starter-pack",
      "versionDetails": [
        {
          "rootPackageVersion": "9.20.15",
          "hoistedVersion": "9.20.15"
        }
      ]
    },
    {
      "packageName": "starter-theme-pack",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "text-block",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "utilities",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "video-player",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    },
    {
      "packageName": "wishlist",
      "versionDetails": [
        {
          "rootPackageVersion": "--",
          "hoistedVersion": "9.20.15",
          "starter-pack-package-json-version": "9.20.15",
          "starter-pack-node-modules-version": "HOISTED: Using version 9.20.15"
        }
      ]
    }
  ],
  "themes": {
    "localThemes": [],
    "installedThemes": []
  }
}`

`MSDyn365_APP_TYPE=partner
PORT=4000
MSDyn365_HOST=parecomm-eval.commerce.dynamics.com
MSDyn365Commerce_BASEURL=https://parecomm5ad4ba92b8ad17e9ret.cloud.retail.dynamics.com/
MSDyn365Commerce_CHANNELID=68719478279
MSDyn365Commerce_CATALOGID=0
MSDyn365Commerce_OUN=128
MSDyn365Commerce_BASEIMAGEURL=https://images-us-sb.cms.commerce.dynamics.com/cms/api/fmcbtrzcss/imageFileData/search?fileName=/
`

**Comment by mkelan** [comment]
Hi Derrick, from what i see, your retail server (https://parecomm5ad4ba92b8ad17e9ret.cloud.retail.dynamics.com/Commerce/GetEnvironmentConfiguration) is on 9.19.20079.6 version. This maps to 10.0.9 build. 

And you are using retail proxy 9.20.15, which maps to 10.0.10 build. This might be the reason for the bad request on your API. I would recommend the following

1. Lock your retail proxy to 9.18.2 (retail servers are backward compatible so should work with older version of retail proxy)
2. Lock below to 9.20.8

"@msdyn365-commerce-modules/starter-pack": "9.20.8",
"@msdyn365-commerce-modules/fabrikam-design-kit": "9.20.8",

And let us know if that works correctly.

thanks!
Murali

**Comment by barlowdw** [comment]
Hi Murali,

Updated the versions and was able to complete the checkout process. Thanks.
Still not able to login.

**Comment by mkelan** [comment]
I will have to check with SMEs here on login. As far as i recall login experience is purely controlled by our backend systems and not something you can customize via partner app (there are different customization steps). Its possible login is broken only on local environment. Do you mind deploying and trying that in the remote instance?

**Comment by barlowdw** [comment]
Will only be able to deploy the the hosted environment tomorrow. I will let you know if the issue is reproduced after deployment.

**Comment by barlowdw** [comment]
Tested on hosted environment with customizations deployed and I am able to login there.

**Comment by mkelan** [comment]
great! thanks for confirmation.
