### ISSUE TITLE
folder public\msdyn365-assets\webfonts missing

### ISSUE THREAD

**Issue by kurthatlevik-inspirit365** [microsoft/Msdyn365.Commerce.Online#50]
Hi.   When trying to un the yarn start to see the site, I saw that font's and icons are missing.

The reason was that folder public\msdyn365-assets\webfonts missing.  I see a folder named "public\webfonts", but it seams that it must be in the folder msdyn365-assets\.

When I created public\msdyn365-assets\webfonts and copied from public\webfonts it started to work again as expected.

@samjarawan, can you validate ?

**Comment by samjarawan** [comment]
Hi Kurt, Yes that is correct, when you leverage the CSS optimization feature, the newer msdyn365-assets directory is needed as documented here: https://docs.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/module-css-optimization#configure-assets-in-css-for-use-with-module-css-optimization

Hope that helps!
Sam
