### ISSUE TITLE
Critical vulnerabilities in packages

### ISSUE THREAD

**Issue by DShalima** [microsoft/Msdyn365.Commerce.Online#57]
There is 20 Critical vulnerabilities in packages right now.
This two as example
<img width="649" alt="Screenshot 2022-07-15 at 13 57 10" src="https://user-images.githubusercontent.com/92512868/179218698-729f1850-d259-4f38-a997-3f38ec8154e2.png">
<img width="649" alt="Screenshot 2022-07-15 at 13 56 33" src="https://user-images.githubusercontent.com/92512868/179218703-9802f4ad-0db5-42a5-b3ad-6e46350c8339.png">

**Comment by mkelan** [comment]
We review the critical vulnerabilities periodically and act on them. Depending on whether the vulnerability is applicable to us (based on whether we use that vulnerable code and how that dependency is used etc.) we either fix them or close them (if its not applicable). Also we dont normally back port these vulnerability fixes, its often fixed forward.
