### ISSUE TITLE
Frontend lagging from long styles dependencies

### ISSUE THREAD

**Issue by kucharzgotuje** [microsoft/Msdyn365.Commerce.Online#58]
Hi! 

We've imported fabrikam as our base theme and we noticed that it's lagging very much from having to long dependencies tree. 
It's taking forever to investigate any element using DevTools. 
I've copied files and fixed it by simply removing all redundant imports from sass files but, still, you should manage your sass better guys. 

I would provide a video but I can't add it anywhere.

**Comment by mkelan** [comment]
Closing this old thread. Please use https://community.dynamics.com/365/commerce/f/dynamics-365-commerce-forum as this is not actively monitored
