### ISSUE TITLE
Pick up option is not working properly

### ISSUE THREAD

**Issue by AmanSonii** [microsoft/Msdyn365.Commerce.Online#59]
Hi experts,

Case 1: Only pick up item is added to cart.
We have enabled pick up options for the products. It works fine while adding pick up location on Product Details Screen.
While on the checkout screen it is showing the delivery options and shipping address it should be disable as items are only for pick up.

Case 2: Pick up is added and then other item added as shipped.
In this case the checkout screen is neither showing delivery options nor shipping address but it is supposed to show as we have one item as shipped in the cart.

In the checkout-delivery-options module the delivery option get configured for the cart, there is it considering only the delivery mode of first line for the cart and updating the same for all lines.

Regards,
Aman

**Comment by mkelan** [comment]
@AmanSonii Issues here are not actively monitored. can you please ask your questions at https://community.dynamics.com/365/commerce/f/dynamics-365-commerce-forum.  Other option is to create a SR.
