### ISSUE TITLE
SDK setup issue with M2 Apple

### ISSUE THREAD

**Issue by nemesisat** [microsoft/Msdyn365.Commerce.Online#66]
Hi 
Currently facing issue to setup sdk in apple MacBook pro M2. give node-sass module issue. anyone face the issue and able to resolve it.

**Comment by bradyd** [comment]
Can you provide the error dump you are getting?

Thanks,
Brady

**Comment by danielkoch** [comment]
Good example why it would makes sense to have an issue template here. Posting issues without relevant information should't be possible.

There is a similar issue/question open: https://github.com/microsoft/Msdyn365.Commerce.Online/issues/63 – but with the old sass implementation used in this project there are a lot more problems that could occur.

**Comment by nemesisat** [comment]
The issue appears using M2 Architecture. I have mac book with Intel processor and it is working fine there. After doing some research I was able to resolve it using Rosetta 2.
