### ISSUE TITLE
EmailRegex utility not matches against top level domain with only numbers and subdomain

### ISSUE THREAD

**Issue by danielkoch** [microsoft/Msdyn365.Commerce.Online#67]
The regex utility for validating email addresses (location in published npm package: `node_modules/@msdyn365-commerce-modules/retail-actions/src/utilities/regex/email-regex.ts`) not working with top level domains that have subdomains and only contain numbers.

Example email address:
testemail@testemail.123.it

The regex must be extended by `0-9`, full regex: `/^[a-zA-Z0-9.!#$%&'*+=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/`

**Comment by anastasiiaandreichuk** [comment]
The bug fix will be available in 9.50 SSK version and later.
