### ISSUE TITLE
Google Map not loading in Store locator page - 365 eCommerce.

### ISSUE THREAD

**Issue by ddaytechnologies** [microsoft/Msdyn365.Commerce.Online#68]
Hi, 

We have done customization on store locator page and added google map functionality.

Location loading properly but google map not loading. PFA.

![GoogleMapError](https://github.com/microsoft/Msdyn365.Commerce.Online/assets/153101831/df6e2e86-7e59-4315-ac8b-6237348e880c)

**Comment by aayushdoda** [comment]
Issue is resolved for the above page by updating the CORS setting in the site builder.
