### ISSUE TITLE
Unable to access config values from within a module

### ISSUE THREAD

**Issue by nick4501** [microsoft/Msdyn365.Commerce.Online#71]
I've created a new module with a custom data action.  I'm trying to read config values from within the data action's "action" function:

    const apiSettings = Msdyn365.msdyn365Commerce.apiSettings;
    const contextValueFromConfig = ctx.requestContext.apiSettings

...but both of these objects are completely empty.  I'm running this locally, via https://localhost:4000/modules?type=xxxxx and also tried this as part of a page mock.

I assumed that these would be populated from the corresponding values in settings\app.settings.json, but this doesn't appear to be the case.  What am I doing wrong?

**Comment by anastasiiaandreichuk** [comment]
Hi @nick4501,
App settings and api settings are different objects.

`app.settings.json` file holds app settings. Those settings can be accessed by using `ctx.requestContext.app.config` in data action's action function.
More information: https://learn.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/app-settings

`apiSettings` can be mocked 3 different ways:
1) [Data action mock](https://learn.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/test-data-action-mocks):
```json
{
    "CacheObjectType": "MyCacheObjectType",
    "CacheKey": "MyCacheKey",
    "Mock": {
      "foo": "bar"      
    },
    "apiSettings": {
       "channelId": 0
     }
}
```

2) [Module mock](https://learn.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/test-module-mock): 
```json
{
    "id": "R1Module1",
    "config": {
      "imageAlignment": "left",
    },
    "data": {
      "actionResponse": {
        "text": "Sample Action Response"
      }
    },
    "typeName": "product-feature",
    "context": {
        "actionContext": {
	    "id": "T1",
	    "requestContext": {
		"locale": "en-us",
		"apiSettings": {
	            "channelId": 0
		}
	    }
        }
    }
}
```

3) [Page mock](https://learn.microsoft.com/en-us/dynamics365/commerce/e-commerce-extensibility/test-page-mock) - as a part of `renderingContext`:
```json
"renderingContext": {
   "apiSettings": {
      "channelId": 0
    },
    "locale": "en-us"
}
```

Please let us know if this worked for you.
